import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const pretendard = localFont({
  src: "../public/fonts/Pretendard-Regular.woff2",
  display: "swap",
  weight: "45 920",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-full my-0 mx-auto h-screen">
      <body
        className={`${pretendard.className} flex min-w-[320px] max-w-[600px] min-h-screen flex-col items-center justify-between px-6`}
      >
        {children}
      </body>
    </html>
  );
}
